version: '3.8'

services:
  postgres-api:
    image: postgres:14.3
    container_name: email-verifier-database
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: 'registration_dev'
      POSTGRES_USER: 'emailverifier'
      POSTGRES_PASSWORD: 'emailverifier'
      ADDITIONAL_POSTGRES_DBS: 'registration_test,notification_dev,notification_test'
    volumes:
      - ./databases/init-scripts:/docker-entrypoint-initdb.d
      - ./.docker-data/.pg-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: email-verifier-rabbit
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq

 #k6:
 #  image: grafana/k6
 #  container_name: k6-load-tester
 #  entrypoint: ["k6"]
 #  command: ["run", "/scripts/test.js"]
 #  ports:
 #    - '8081:8081'
 #  volumes:
 #    - ./:/scripts
 #  networks:
 #    - email-verifier-network

networks:
  email-verifier-network:
    driver: bridge

configs:
  plugins:
    content: "[rabbitmq_consistent_hash_exchange]."
